issue
2025-06-02 12:07:02.600 10764-10764 SnipActivity            com.example.snipshot                 D  User clicked ALLOW on screen capture permission
2025-06-02 12:07:02.610 10764-10764 AndroidRuntime          com.example.snipshot                 D  Shutting down VM
2025-06-02 12:07:02.612 10764-10764 AndroidRuntime          com.example.snipshot                 E  FATAL EXCEPTION: main
                                                                                                    Process: com.example.snipshot, PID: 10764
                                                                                                    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1001, result=-1, data=Intent { (has extras) }} to activity {com.example.snipshot/com.example.snipshot.SnipActivity}: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
                                                                                                    	at android.app.ActivityThread.deliverResults(ActivityThread.java:5655)
                                                                                                    	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5694)
                                                                                                    	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2462)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:240)
                                                                                                    	at android.os.Looper.loop(Looper.java:351)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8377)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
                                                                                                    Caused by: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3062)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3046)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3029)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2971)
                                                                                                    	at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:268)
                                                                                                    	at android.media.projection.MediaProjection.<init>(MediaProjection.java:63)
                                                                                                    	at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:134)
                                                                                                    	at com.example.snipshot.SnipActivity.onActivityResult(SnipActivity.kt:44)
                                                                                                    	at android.app.Activity.dispatchActivityResult(Activity.java:8731)
                                                                                                    	at android.app.ActivityThread.deliverResults(ActivityThread.java:5648)
                                                                                                    	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5694) 
                                                                                                    	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67) 
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2462) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:240) 
                                                                                                    	at android.os.Looper.loop(Looper.java:351) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8377) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013) 
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:626)
                                                                                                    	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:163)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1331)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1268)
2025-06-02 12:07:02.635 10764-10764 Process                 com.example.snipshot                 I  Sending signal. PID: 10764 SIG: 9
---------------------------- PROCESS ENDED (10764) for package com.example.snipshot ----------------------------